name: Scrape Football Matches Ligue 1

on:
  workflow_dispatch:
  
  repository_dispatch:
    types:
      - webhook
  
  schedule:
   - cron: "0 12,0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: true
      - run: |
          node scraping/matchesLigue1.js
          git config --global user.email bot@zeus.com
          git config --global user.name zeus-api-bot
          git add -A
          git commit -am "[bot] update Zeus database"
          git pull --rebase origin main
          git push -f origin main
