name: Scrape Football Scorers

on:
  workflow_dispatch:
  
  repository_dispatch:
    types:
      - webhook
  
  schedule:
   - cron: "0 2 * * 6,0,1,2"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true
      - run: |
          node scraping/scorers.js
          git config user.name zeus-api-bot
          git diff --quiet && git diff --staged --quiet || git commit -am "[bot] update Zeus database"
          git push origin main
