name: Scrape Football Data

on:
  workflow_dispatch:
  
  repository_dispatch:
    types:
      - webhook
  
  schedule:
   - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true
      - run:
          node scraping/index.js
          git config user.name zeus-api-bot
          git status
          git add -A
          git status
          git commit -m "[bot] update Zeus database"
          git push origin main
