name: Scrape Football Standings

on:
  workflow_dispatch:
  
  repository_dispatch:
    types:
      - webhook
  
  schedule:
   - cron: "0 12,0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: true
      - run: |
          node scraping/standings.js
          # Crea o actualiza un archivo para forzar un cambio
          echo "Run on $(date)" > last_workflow_run_standings.txt
          git config --global user.email bot@footballr.com
          git config --global user.name footballr-api-bot
          git add -A
          git commit -am "[bot] update FootballR database"
          git pull --rebase origin main
          git push -f origin main
