name: Scrape Football Data

on:
  workflow_dispatch:
  
  repository_dispatch:
    types:
      - webhook
  
  schedule:
   - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run:
          npm install puppeteer@18.1.0
          node scraping/index.js
          git config user.name zeus-api-bot
          git add -A
          git commit -m "[bot] UPDATE zeus-api database"
          git push origin main
