name: Scrape Football Matches Ligue 1

on:
  workflow_dispatch:
  
  repository_dispatch:
    types:
      - webhook
  
  schedule:
   - cron: "0 2 * * 6,0,1,2"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true
      - run: |
          node scraping/matchesLigue1.js
          git config --global user.name zeus-api-bot
          git config user.name 
          git add -A
          git commit -am "[bot] update Zeus database"
          git pull --rebase origin main
          git push -f origin main
